In [24]:
import numpy as np

In [25]:
kanto = np.array([73, 67, 43])

In [26]:
kanto

array([73, 67, 43])

In [27]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [28]:
weights = np.array([w1, w2, w3])

In [29]:
weights

array([0.3, 0.2, 0.5])

In [30]:
type(weights)

numpy.ndarray

In [31]:
weights[0]

0.3

In [32]:
np.dot(kanto, weights)

56.8

In [33]:
(kanto * weights).sum()

56.8

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [35]:
arr1 * arr2

array([ 4, 10, 18])

In [36]:
arr2.sum()

15

In [37]:
#python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000))

In [38]:
#numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [39]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

Wall time: 279 ms


333332833333500000

%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

In [40]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 997 µs


584144992

In [ ]:
#.dot() is faster than the for loop

In [41]:
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]])

In [42]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [43]:
climate_data.shape

(5, 3)

In [44]:
weights

array([0.3, 0.2, 0.5])

In [45]:
weights.shape

(3,)

In [46]:
#3d array
arr3 = np.array([
    [[11, 12, 13],
    [13, 14, 15]],
    
    [[15, 16, 17],
    [17, 18, 19.5]]
])

In [47]:
arr3.shape

(2, 2, 3)

In [48]:
arr3.dtype

dtype('float64')

In [49]:
climate_data.dtype

dtype('int32')

In [50]:
weights.dtype

dtype('float64')

In [55]:
#matrix multiplication
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [56]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [57]:
import urllib.request

#download climate csv and save as .txt
urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x28206875e80>)

In [58]:
#load the data
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [61]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [62]:
climate_data.shape

(10000, 3)

In [63]:
weights = np.array([0.3, 0.2, 0.5])

In [64]:
yields = climate_data @ weights

In [65]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [66]:
yields.shape

(10000,)

In [67]:
# add yields back to the data as a new column
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [71]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [78]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt = '%.2f',
           header='temperature,rainfall,humidity, yield_apples', 
           comments = '')

#  Arithmetic operations, broadcasting and comparison

In [79]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [80]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [81]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [82]:
# Element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [83]:
# Division by scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [84]:
# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [85]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

#  Array Broadcasting

In [86]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [87]:
arr2.shape

(3, 4)

In [88]:
arr4 = np.array([4, 5, 6, 7])

In [89]:
arr4.shape

(4,)

In [90]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

#  Array Comparison

In [91]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [92]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [93]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [94]:
(arr1 == arr2).sum()

3

## Array indexing and slicing

Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [95]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [96]:
arr3.shape

(3, 2, 4)

In [97]:
# Single element
arr3[1, 1, 2]

36.0

In [98]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])